### ISSUE TITLE
Question about porting to VSCode

### ISSUE THREAD

**Issue by benadamstyles** [DanielPintilei/atom-loved-syntax#2]
Hi! I have just started using VSCode for various reasons after being a long-time Atom user, and the thing I miss most is your theme, which is the best I've ever come across. Before I invest time in porting it to a TextMate plist file, I have 2 questions:

1. Have you already ported it, or thought about doing so?
2. If not, are you ok with me doing it? Would you be able to help if I have any problems?

Thanks so much!

**Comment by DanielPintilei** [comment]
Hi. I thought about porting it to different apps and also making a website for it, like the Cake one. I'm ok with you porting it. It's easy to do it with https://tmtheme-editor.herokuapp.com :)

**Comment by benadamstyles** [comment]
Ah that link is exactly what I was looking for, thanks! Well I will have a go, but I'll show it to you once it's done and I won't publish it in case you want to.

**Comment by benadamstyles** [comment]
Hey, sorry I haven't got round to it. There was more to think about than just porting it, as there seem to be far more options in a tmtheme than in an atom theme... in any case, it seemed beyond my design/colour expertise. I still miss this theme in vscode though!

**Comment by DanielPintilei** [comment]
No problem. I will port it if i find the time.

**Comment by benadamstyles** [comment]
Just FYI I stumbled across this yesterday – my prayers (and yours maybe?!) have been answered! https://github.com/josefaidt/rouge-theme
