### ISSUE TITLE
Secondary fonts

### ISSUE THREAD

**Issue by oddhorse** [DanielPintilei/atom-loved-syntax#5]
How do you change which parts of the code are shown in the secondary font?

I know it has something to do with this, but I don't know exactly this means:
![screen shot 2017-08-21 at 8 12 29 pm](https://user-images.githubusercontent.com/15389659/29543163-237ac7fa-86ad-11e7-9f1a-01d2fb29a695.png)

**Comment by DanielPintilei** [comment]
https://github.com/DanielPintilei/atom-loved-syntax/issues/4

**Comment by oddhorse** [comment]
Well, I know that putting in different things such as .syntax--keyword makes that particular part show up in the secondary font, but I want things such as if statements in the second font, much like variables are with your stylesheet.  I don't know what goes to what with the syntax selectors, though.  Is there any list of those anywhere?

**Comment by DanielPintilei** [comment]
I don't know any

**Comment by oddhorse** [comment]
Ok, where did you learn those selectors then?

**Comment by DanielPintilei** [comment]
I don't have the links
